services:
  - type: web
    name: land-by-alex
    env: python
    runtime: python-3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    healthCheckPath: /test
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: land-listings-db
          property: connectionString
    disk:
      name: land-uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1

databases:
  - name: land-listings-db
    databaseName: land_listings
    user: land_user
    plan: free

# Optional: Static site for assets (if needed later)
# - type: static
#   name: land-assets
#   buildCommand: echo "No build needed"
#   staticPublishPath: static